x-common: &x-common
  build:
    context: .
    dockerfile: Dockerfile
  init: true
  environment:
    MPI_HOSTS: h1,h2,h3,h4
  volumes:
    - .:/workspaces/peanuts-playground:cached
    - spack-root:/home/vscode/.cache/spack
    - spack-settings:/home/vscode/.spack
  networks:
    - peanuts_net
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp:unconfined
  privileged: true
  command: >
    bash -c "sudo service ssh restart && sleep infinity"

services:
  h1:
    <<: *x-common
    hostname: h1
    container_name: peanuts-h1
  h2:
    <<: *x-common
    hostname: h2
    container_name: peanuts-h2
  h3:
    <<: *x-common
    hostname: h3
    container_name: peanuts-h3
  h4:
    <<: *x-common
    hostname: h4
    container_name: peanuts-h4

networks:
  peanuts_net:

volumes:
  spack-root:
  spack-settings:
